services:
  app:
    build: ./game
    ports:
      - "8080:5000"
    restart: on-failure
    depends_on:
      - "db"
  db:
    image: mongo
    expose:
      - "27017"
    restart: on-failure
    volumes:
      - ./database_storage_folder:/data/db